### ISSUE TITLE
Create HTML website

### ISSUE THREAD

**Issue by RealConrad** [RealConrad/42webserv#2]
## Create the basic HTML files
To test our webserv we will need to serve a static website as per the requirements where we can show the basic functionality of our webserv (see image)

![image](https://github.com/RealConrad/42webserv/assets/79513076/b08b692e-38fb-4c59-931a-83b15a738124)

### To-do
- [x] index.html
- [x] Any component files

The website should demonstrate the following:
- [x] Upload files (POST/PUT)
- [x] Delete files - DELETE
- [x] View data (e.g. some images) - GET

### Nice to haves (not mandatory)
- [x] Basic CSS
